import { readFile, mkdir, copyFile } from 'node:fs/promises';
import { build } from 'esbuild';
import { validateDevLogEntries, assertDevLogReleaseAlignment } from '@aribradshaw/devlog';
const releases = JSON.parse(await readFile('config/devlog-releases.json', 'utf8'));
const pkg = JSON.parse(await readFile('package.json', 'utf8'));
if (!validateDevLogEntries(releases, { rejectAuthorEmail: true, rejectTicketTitle: true })) throw new Error('Invalid public DevLog entries');
assertDevLogReleaseAlignment({currentVersion:pkg.version,latestDevLogVersion:releases[0].version,dependencyVersion:pkg.dependencies['@aribradshaw/devlog']});
await mkdir('site/dist', {recursive:true});
for (const file of ['index.html', 'style.css']) await copyFile(`site/${file}`, `site/dist/${file}`);
await build({ entryPoints:['site/main.js'],bundle:true,minify:true,format:'esm',outfile:'site/dist/main.js',define:{'BUILD_COMMIT':JSON.stringify(process.env.GITHUB_SHA||'')} });
console.log(`Public DevLog built for ${pkg.version} using @aribradshaw/devlog.`);
